package br.edu.qi.model;
// Generated 05/10/2017 20:18:38 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco",
        catalog = "dbrh"
)
public class Endereco implements java.io.Serializable {

    private Integer idendereco;
    private String rua;
    private int numero;
    private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Endereco() {
    }

    public Endereco(String rua, int numero) {
        this.rua = rua;
        this.numero = numero;
    }

    public Endereco(String rua, int numero, Set<Pessoa> pessoas) {
        this.rua = rua;
        this.numero = numero;
        this.pessoas = pessoas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idendereco", unique = true, nullable = false)

    public Integer getIdendereco() {
        return this.idendereco;
    }

    public void setIdendereco(Integer idendereco) {
        this.idendereco = idendereco;
    }

    @Column(name = "rua", nullable = false, length = 100)
    public String getRua() {
        return this.rua;
    }

    public void setRua(String rua) {
        this.rua = rua;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }

    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }

}
