/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bibliotecavirtual.GerenciadorBibliotecaVirtual;
import javax.swing.JOptionPane;
import usuario.GerenciadorUsuario;

/**
 *
 * @author Luis Gustavo
 */
public class FrmAlterarSenha extends javax.swing.JFrame {

    /**
     * Creates new form FrmAlterarSenha
     */
    public FrmAlterarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfirmacaoNovaSenha = new javax.swing.JLabel();
        btnSalvarNovaSenha = new javax.swing.JButton();
        lblNovaSenha1 = new javax.swing.JLabel();
        txtConfirmacaoNovaSenha = new javax.swing.JPasswordField();
        txtNovaSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de senha");
        setResizable(false);

        lblConfirmacaoNovaSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConfirmacaoNovaSenha.setText("Confirmação:");

        btnSalvarNovaSenha.setText("Salvar");
        btnSalvarNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNovaSenhaActionPerformed(evt);
            }
        });

        lblNovaSenha1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNovaSenha1.setText("Nova Senha:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNovaSenha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarNovaSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConfirmacaoNovaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmacaoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovaSenha1)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmacaoNovaSenha)
                    .addComponent(txtConfirmacaoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarNovaSenha)
                    .addComponent(btnVoltar))
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNovaSenhaActionPerformed
        GerenciadorUsuario gerenciadorUsuario = new GerenciadorUsuario();
        if (txtNovaSenha.getText().equals(txtConfirmacaoNovaSenha.getText()) && gerenciadorUsuario.isVerificadorSenhas(txtConfirmacaoNovaSenha.getText())) {
            int controle = JOptionPane.showConfirmDialog(this, "Confirma a operação?", "Alteração de senha", JOptionPane.OK_CANCEL_OPTION);
            switch (controle) {
                case 0:
                    boolean statusAlteracao = GerenciadorBibliotecaVirtual.isAlteracaoArquivoUsuarioSenha(txtConfirmacaoNovaSenha.getText());
                    if (statusAlteracao) {
                        JOptionPane.showMessageDialog(this, "Alteração realizada com sucesso!");
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro!, por favor, verificar com o administrador!");
                    }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Senha não confere! \n"
                    + "Ou números de caracteres menor que 3!");
        }
    }//GEN-LAST:event_btnSalvarNovaSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarNovaSenha;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblConfirmacaoNovaSenha;
    private javax.swing.JLabel lblNovaSenha1;
    private javax.swing.JPasswordField txtConfirmacaoNovaSenha;
    private javax.swing.JPasswordField txtNovaSenha;
    // End of variables declaration//GEN-END:variables
}
