/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bibliotecavirtual.GerenciadorBibliotecaVirtual;
import bibliotecavirtual.Livro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Gustavo
 */
public class FrmLivro extends javax.swing.JFrame {

    /**
     * Creates new form FrmLivro
     */
    public FrmLivro() {
        initComponents();
        carregarTabela();
    }

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaLivros.getModel();
        String lista[] = new String[5];
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        GerenciadorBibliotecaVirtual.livros.forEach((Livro l) -> {
            lista[0] = l.getNome();
            lista[1] = l.getAutor();
            lista[2] = String.valueOf(l.getNumeroPaginas());
            lista[3] = l.getEditora();
            lista[4] = l.getConteudo();
            modelo.addRow(lista);
        });

    }

    private void limparCampos() {
        txtNomeLivro.setText("");
        txtAutorLivro.setText("");
        txtEditoraLivro.setText("");
        txtNumeroPaginasLivro.setText("");
        txtConteudoLivro.setText("");
    }

    private int rowIndex() {
        return tabelaLivros.getSelectedRow();
    }

    /**
     * Retorna a String contida na matriz de Jtable, passando linha e coluna
     * como parametro.
     *
     * @param linha
     * @param coluna
     * @return
     */
    private String retornaStringLinhaColuna(int linha, int coluna) {
        try {
            return tabelaLivros.getValueAt(linha, coluna).toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não encontrado!");
            return null;
        }
    } 

    /**
     * Novo Livro Para ativar o JOptionPane passe o valor 1 para sim e 2 não
     *
     * @param controlador 1 = Sim 0 = não
     */
    private void novoLivro(int controlador) {
        if (txtNomeLivro.getText().isEmpty() || txtAutorLivro.getText().isEmpty() || txtNumeroPaginasLivro.getText().isEmpty()
                || txtEditoraLivro.getText().isEmpty() || txtConteudoLivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro, não foi possivel cadastrar livro!\nPreencha todos os campos!");
        } else {
            boolean status = GerenciadorBibliotecaVirtual.isCadastrarArquivoLivro(txtNomeLivro.getText(), txtAutorLivro.getText(), Integer.parseInt(txtNumeroPaginasLivro.getText()), txtEditoraLivro.getText(), txtConteudoLivro.getText());
            if (status) {
                limparCampos();
                carregarTabela();
                switch (controlador) {
                    case 1:
                        JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");
                }
            }
        }
    }

    private void excluirLivro(Livro livro) {
        GerenciadorBibliotecaVirtual.isExclusaoLivro(livro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        btnNovoLivro = new javax.swing.JButton();
        btnSalvarLivro = new javax.swing.JButton();
        btnExcluirLivro = new javax.swing.JButton();
        btnAtualizarLivro = new javax.swing.JButton();
        btnVoltarLivro = new javax.swing.JButton();
        lblNomeLivro = new javax.swing.JLabel();
        lblAutorLivro = new javax.swing.JLabel();
        lblNumeroPaginasLivro = new javax.swing.JLabel();
        lblEditoraLivro = new javax.swing.JLabel();
        txtNomeLivro = new javax.swing.JTextField();
        txtAutorLivro = new javax.swing.JTextField();
        txtNumeroPaginasLivro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConteudoLivro = new javax.swing.JTextArea();
        lblConteudo = new javax.swing.JLabel();
        txtEditoraLivro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros");
        setResizable(false);

        tabelaLivros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor", "Nº Pág.", "Editora", "Conteúdo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLivros);
        if (tabelaLivros.getColumnModel().getColumnCount() > 0) {
            tabelaLivros.getColumnModel().getColumn(2).setMinWidth(50);
            tabelaLivros.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        btnNovoLivro.setText("Novo");
        btnNovoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLivroActionPerformed(evt);
            }
        });

        btnSalvarLivro.setText("Salvar");
        btnSalvarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLivroActionPerformed(evt);
            }
        });

        btnExcluirLivro.setText("Excluir");
        btnExcluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLivroActionPerformed(evt);
            }
        });

        btnAtualizarLivro.setText("Atualizar");
        btnAtualizarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarLivroActionPerformed(evt);
            }
        });

        btnVoltarLivro.setText("Voltar");
        btnVoltarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLivroActionPerformed(evt);
            }
        });

        lblNomeLivro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNomeLivro.setText("Nome");

        lblAutorLivro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAutorLivro.setText("Autor");

        lblNumeroPaginasLivro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNumeroPaginasLivro.setText("Nº Páginas");

        lblEditoraLivro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEditoraLivro.setText("Editora");

        txtNomeLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAutorLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNumeroPaginasLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtConteudoLivro.setColumns(20);
        txtConteudoLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtConteudoLivro.setLineWrap(true);
        txtConteudoLivro.setRows(5);
        jScrollPane2.setViewportView(txtConteudoLivro);

        lblConteudo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConteudo.setText("Conteúdo");

        txtEditoraLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAutorLivro)
                                .addGap(21, 21, 21)
                                .addComponent(txtAutorLivro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroPaginasLivro)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroPaginasLivro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditoraLivro)
                                .addGap(8, 8, 8)
                                .addComponent(txtEditoraLivro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNomeLivro)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNovoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSalvarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnExcluirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAtualizarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnVoltarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblConteudo)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeLivro)
                    .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConteudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutorLivro)
                            .addComponent(txtAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroPaginasLivro)
                            .addComponent(txtNumeroPaginasLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEditoraLivro)
                            .addComponent(txtEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtualizarLivro)
                            .addComponent(btnExcluirLivro)
                            .addComponent(btnSalvarLivro)
                            .addComponent(btnNovoLivro)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarLivro)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLivroActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarLivroActionPerformed

    private void btnAtualizarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarLivroActionPerformed
        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnAtualizarLivroActionPerformed

    private void tabelaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLivrosMouseClicked
        txtNomeLivro.setText(retornaStringLinhaColuna(rowIndex(), 0));
        txtAutorLivro.setText(retornaStringLinhaColuna(rowIndex(), 1));
        txtEditoraLivro.setText(retornaStringLinhaColuna(rowIndex(), 3));
        txtNumeroPaginasLivro.setText(retornaStringLinhaColuna(rowIndex(), 2));
        txtConteudoLivro.setText(retornaStringLinhaColuna(rowIndex(), 4));
    }//GEN-LAST:event_tabelaLivrosMouseClicked

    private void btnNovoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLivroActionPerformed
        novoLivro(1);
    }//GEN-LAST:event_btnNovoLivroActionPerformed

    private void btnExcluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLivroActionPerformed
        if (tabelaLivros.getSelectedRow() > 0) {
            Livro livro = new Livro(retornaStringLinhaColuna(rowIndex(), 0), retornaStringLinhaColuna(rowIndex(), 1), Integer.parseInt(retornaStringLinhaColuna(rowIndex(), 2)), retornaStringLinhaColuna(rowIndex(), 3), retornaStringLinhaColuna(rowIndex(), 4));
            ((DefaultTableModel) tabelaLivros.getModel()).removeRow(tabelaLivros.getSelectedRow());
            boolean status = GerenciadorBibliotecaVirtual.isExclusaoLivro(livro);
            if (status) {
                carregarTabela();
                limparCampos();
                JOptionPane.showMessageDialog(this, "Livro excluido com sucesso!");
            }
        } else {
            carregarTabela();
            limparCampos();
            JOptionPane.showMessageDialog(this, "Erro!");
        }
    }//GEN-LAST:event_btnExcluirLivroActionPerformed

    private void btnSalvarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLivroActionPerformed
        Livro livroAnterior = new Livro(retornaStringLinhaColuna(rowIndex(), 0), retornaStringLinhaColuna(rowIndex(), 1), Integer.parseInt(retornaStringLinhaColuna(rowIndex(), 2)), retornaStringLinhaColuna(rowIndex(), 3), retornaStringLinhaColuna(rowIndex(), 4));
        Livro livroNovo = new Livro(txtNomeLivro.getText(), txtAutorLivro.getText(), Integer.parseInt(txtNumeroPaginasLivro.getText()), txtEditoraLivro.getText(), txtConteudoLivro.getText());
        if (!livroNovo.equals(livroAnterior)) {
            novoLivro(0);
            GerenciadorBibliotecaVirtual.isExclusaoLivro(livroAnterior);
            limparCampos();
            carregarTabela();
            JOptionPane.showMessageDialog(this, "Livro alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro!");
        }
    }//GEN-LAST:event_btnSalvarLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarLivro;
    private javax.swing.JButton btnExcluirLivro;
    private javax.swing.JButton btnNovoLivro;
    private javax.swing.JButton btnSalvarLivro;
    private javax.swing.JButton btnVoltarLivro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAutorLivro;
    private javax.swing.JLabel lblConteudo;
    private javax.swing.JLabel lblEditoraLivro;
    private javax.swing.JLabel lblNomeLivro;
    private javax.swing.JLabel lblNumeroPaginasLivro;
    private javax.swing.JTable tabelaLivros;
    private javax.swing.JTextField txtAutorLivro;
    private javax.swing.JTextArea txtConteudoLivro;
    private javax.swing.JTextField txtEditoraLivro;
    private javax.swing.JTextField txtNomeLivro;
    private javax.swing.JTextField txtNumeroPaginasLivro;
    // End of variables declaration//GEN-END:variables
}
