/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilha;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author luizfduartejr
 */
public class FrmJogo extends javax.swing.JFrame {

    private int movimentos = 0;
    
    private JButton[] botoesX = new JButton[3];
    private JButton[] botoesY = new JButton[3];
    private JButton[] botoesZ = new JButton[3];
    
    private Pilha<Integer> X = new Pilha<>();
    private Pilha<Integer> Y = new Pilha<>();
    private Pilha<Integer> Z = new Pilha<>();
    
    private Map<String, JButton[]> mapButtons = new HashMap<>();
    private Map<String, Pilha<Integer>> mapPilhas = new HashMap<>();
    
    /**
     * Creates new form FrmJogo
     */
    public FrmJogo() {
        initComponents();
    
        X.push(3);
        X.push(2);
        X.push(1);
        
        botoesX[0] = btnX1;
        botoesX[1] = btnX2;
        botoesX[2] = btnX3;
        configurarBotoes(botoesX);
        btnX1.setText("3");
        btnX2.setText("2");
        btnX3.setText("1");
        
        botoesY[0] = btnY1;
        botoesY[1] = btnY2;
        botoesY[2] = btnY3;
        configurarBotoes(botoesY);
        
        botoesZ[0] = btnZ1;
        botoesZ[1] = btnZ2;
        botoesZ[2] = btnZ3;
        configurarBotoes(botoesZ);
        
        mapButtons.put("X", botoesX);
        mapButtons.put("Y", botoesY);
        mapButtons.put("Z", botoesZ);
        
        mapPilhas.put("X", X);
        mapPilhas.put("Y", Y);
        mapPilhas.put("Z", Z);
    }
    
    private void configurarBotoes(JButton[] botoes){
        for (int i = 0; i < botoes.length; i++) {
            botoes[i].setText(" ");
            botoes[i].setSize(50,50);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnX1 = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnX3 = new javax.swing.JButton();
        btnY1 = new javax.swing.JButton();
        btnY2 = new javax.swing.JButton();
        btnY3 = new javax.swing.JButton();
        btnZ3 = new javax.swing.JButton();
        btnZ1 = new javax.swing.JButton();
        btnZ2 = new javax.swing.JButton();
        cmbPop = new javax.swing.JComboBox<>();
        cmbPush = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Torre de Hanói");

        btnX1.setText("jButton1");
        btnX1.setEnabled(false);
        btnX1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1.setPreferredSize(new java.awt.Dimension(50, 50));

        btnX2.setText("jButton1");
        btnX2.setEnabled(false);
        btnX2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2.setPreferredSize(new java.awt.Dimension(50, 50));

        btnX3.setText("jButton1");
        btnX3.setEnabled(false);
        btnX3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY1.setText("jButton1");
        btnY1.setEnabled(false);
        btnY1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY1.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY2.setText("jButton1");
        btnY2.setEnabled(false);
        btnY2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY2.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY3.setText("jButton1");
        btnY3.setEnabled(false);
        btnY3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY3.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ3.setText("jButton1");
        btnZ3.setEnabled(false);
        btnZ3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ3.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ1.setText("jButton1");
        btnZ1.setEnabled(false);
        btnZ1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ1.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ2.setText("jButton1");
        btnZ2.setEnabled(false);
        btnZ2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ2.setPreferredSize(new java.awt.Dimension(50, 50));

        cmbPop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "PopX", "PopY", "PopZ" }));

        cmbPush.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Push", "PushX", "PushY", "PushZ" }));

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbPop, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPush, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnZ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPush, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        String sOrigem = cmbPop.getSelectedItem().toString().replace("Pop", "");
        String sDestino = cmbPush.getSelectedItem().toString().replace("Push", "");
        if(sOrigem.equals("") || sDestino.equals(""))
            return;
        
        trocar(mapButtons.get(sDestino), mapButtons.get(sOrigem), mapPilhas.get(sDestino), mapPilhas.get(sOrigem));
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void trocar(JButton[] bDestino, JButton[] bOrigem, Pilha<Integer> pDestino, Pilha<Integer> pOrigem){
        
        if(pOrigem.top() != null && pDestino.top() != null
                && pOrigem.top() > pDestino.top()){
            JOptionPane.showMessageDialog(this, "Movimento inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        movimentos++;
        lblTitulo.setText("Movimentos:" + movimentos);
        
        Integer valor = pOrigem.pop();
        if(valor == null) return;

        pDestino.push(valor);
        
        bDestino[pDestino.getSize() -1].setText(valor+"");
        bOrigem[pOrigem.getSize()].setText(" ");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnX1;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnX3;
    private javax.swing.JButton btnY1;
    private javax.swing.JButton btnY2;
    private javax.swing.JButton btnY3;
    private javax.swing.JButton btnZ1;
    private javax.swing.JButton btnZ2;
    private javax.swing.JButton btnZ3;
    private javax.swing.JComboBox<String> cmbPop;
    private javax.swing.JComboBox<String> cmbPush;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
