/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilha;

import javax.swing.JButton;

/**
 *
 * @author luizfduartejr
 */
public class FrmJogo extends javax.swing.JFrame {

    private JButton[] botoesX = new JButton[4];
    private JButton[] botoesY = new JButton[4];
    private JButton[] botoesZ = new JButton[4];
    
    private Pilha<String> X = new Pilha<>();
    private Pilha<String> Y = new Pilha<>();
    private Pilha<String> Z = new Pilha<>();
    
    /**
     * Creates new form FrmJogo
     */
    public FrmJogo() {
        initComponents();
    
        X.push("a");
        X.push("b");
        X.push("c");
        X.push("d");
        
        botoesX[0] = btnX1;
        botoesX[1] = btnX2;
        botoesX[2] = btnX3;
        botoesX[3] = btnX4;
        configurarBotoes(botoesX);
        btnX1.setText("a");
        btnX2.setText("b");
        btnX3.setText("c");
        btnX4.setText("d");
        
        botoesY[0] = btnY1;
        botoesY[1] = btnY2;
        botoesY[2] = btnY3;
        botoesY[3] = btnY4;
        configurarBotoes(botoesY);
        
        botoesZ[0] = btnZ1;
        botoesZ[1] = btnZ2;
        botoesZ[2] = btnZ3;
        botoesZ[3] = btnZ4;
        configurarBotoes(botoesZ);
    }
    
    private void configurarBotoes(JButton[] botoes){
        for (int i = 0; i < botoes.length; i++) {
            botoes[i].setText(" ");
            botoes[i].setSize(50,50);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnX1 = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnX3 = new javax.swing.JButton();
        btnX4 = new javax.swing.JButton();
        btnY1 = new javax.swing.JButton();
        btnY2 = new javax.swing.JButton();
        btnY3 = new javax.swing.JButton();
        btnY4 = new javax.swing.JButton();
        btnZ3 = new javax.swing.JButton();
        btnZ4 = new javax.swing.JButton();
        btnZ1 = new javax.swing.JButton();
        btnZ2 = new javax.swing.JButton();
        chkY = new javax.swing.JCheckBox();
        chkX = new javax.swing.JCheckBox();
        chkZ = new javax.swing.JCheckBox();
        btnTrocarParaDireita = new javax.swing.JButton();
        btnTrocarParaEsquerda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jogo de Pilha");

        btnX1.setText("jButton1");
        btnX1.setEnabled(false);
        btnX1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX1.setPreferredSize(new java.awt.Dimension(50, 50));

        btnX2.setText("jButton1");
        btnX2.setEnabled(false);
        btnX2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX2.setPreferredSize(new java.awt.Dimension(50, 50));

        btnX3.setText("jButton1");
        btnX3.setEnabled(false);
        btnX3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX3.setPreferredSize(new java.awt.Dimension(50, 50));

        btnX4.setText("jButton1");
        btnX4.setEnabled(false);
        btnX4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnX4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnX4.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY1.setText("jButton1");
        btnY1.setEnabled(false);
        btnY1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY1.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY2.setText("jButton1");
        btnY2.setEnabled(false);
        btnY2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY2.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY3.setText("jButton1");
        btnY3.setEnabled(false);
        btnY3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY3.setPreferredSize(new java.awt.Dimension(50, 50));

        btnY4.setText("jButton1");
        btnY4.setEnabled(false);
        btnY4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnY4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnY4.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ3.setText("jButton1");
        btnZ3.setEnabled(false);
        btnZ3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ3.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ4.setText("jButton1");
        btnZ4.setEnabled(false);
        btnZ4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ4.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ1.setText("jButton1");
        btnZ1.setEnabled(false);
        btnZ1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ1.setPreferredSize(new java.awt.Dimension(50, 50));

        btnZ2.setText("jButton1");
        btnZ2.setEnabled(false);
        btnZ2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnZ2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnZ2.setPreferredSize(new java.awt.Dimension(50, 50));

        chkY.setText("Y");

        chkX.setText("X");

        chkZ.setText("Z");

        btnTrocarParaDireita.setText("Trocar >");
        btnTrocarParaDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarParaDireitaActionPerformed(evt);
            }
        });

        btnTrocarParaEsquerda.setText("< Trocar");
        btnTrocarParaEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarParaEsquerdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkX)
                                .addGap(18, 18, 18)
                                .addComponent(chkY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(chkZ))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTrocarParaEsquerda)
                                    .addComponent(btnTrocarParaDireita))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkX)
                    .addComponent(chkY)
                    .addComponent(chkZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrocarParaDireita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrocarParaEsquerda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trocar(JButton[] bDestino, JButton[] bOrigem, Pilha<String> pDestino, Pilha<String> pOrigem){
        String valor = pOrigem.pop();
        if(valor == null) return;
        pDestino.push(valor);
        bDestino[pDestino.getSize() -1].setText(valor);
        bOrigem[pOrigem.getSize()].setText(" ");
    }
    private void btnTrocarParaDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarParaDireitaActionPerformed
        if(chkX.isSelected() && chkY.isSelected()){
            trocar(botoesY, botoesX, Y, X);
        }
        else if(chkX.isSelected() && chkZ.isSelected()){
            trocar(botoesZ, botoesX, Z, X);
        }
        else if(chkY.isSelected() && chkZ.isSelected()){
            trocar(botoesZ, botoesY, Z, Y);
        }
    }//GEN-LAST:event_btnTrocarParaDireitaActionPerformed
    private void btnTrocarParaEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarParaEsquerdaActionPerformed
        if(chkX.isSelected() && chkY.isSelected()){
            trocar(botoesX, botoesY, X, Y);
        }
        else if(chkX.isSelected() && chkZ.isSelected()){
            trocar(botoesX, botoesZ, X, Z);
        }
        else if(chkY.isSelected() && chkZ.isSelected()){
            trocar(botoesY, botoesZ, Y, Z);
        }
    }//GEN-LAST:event_btnTrocarParaEsquerdaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrocarParaDireita;
    private javax.swing.JButton btnTrocarParaEsquerda;
    private javax.swing.JButton btnX1;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnX3;
    private javax.swing.JButton btnX4;
    private javax.swing.JButton btnY1;
    private javax.swing.JButton btnY2;
    private javax.swing.JButton btnY3;
    private javax.swing.JButton btnY4;
    private javax.swing.JButton btnZ1;
    private javax.swing.JButton btnZ2;
    private javax.swing.JButton btnZ3;
    private javax.swing.JButton btnZ4;
    private javax.swing.JCheckBox chkX;
    private javax.swing.JCheckBox chkY;
    private javax.swing.JCheckBox chkZ;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
