/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torrehanoi;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Gustavo
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private JButton[] botoesX = new JButton[4];
    private JButton[] botoesY = new JButton[4];
    private JButton[] botoesZ = new JButton[4];

    Pilha X = new Pilha();
    Pilha Y = new Pilha();
    Pilha Z = new Pilha();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        inicializador();
    }

    private void inicializador() {
        X.push(4);
        X.push(3);
        X.push(2);
        X.push(1);

        btnX1.setText("4");
        btnX2.setText("3");
        btnX3.setText("2");
        btnX4.setText("1");

        botoesX[0] = btnX1;
        botoesX[1] = btnX2;
        botoesX[2] = btnX3;
        botoesX[3] = btnX4;

        botoesY[0] = btnY1;
        botoesY[1] = btnY2;
        botoesY[2] = btnY3;
        botoesY[3] = btnY4;

        botoesZ[0] = btnZ1;
        botoesZ[1] = btnZ2;
        botoesZ[2] = btnZ3;
        botoesZ[3] = btnZ4;
    }

    private boolean isVerificadorCheckBox() {
        return (cbX.isSelected() && cbY.isSelected() && cbZ.isSelected());
    }

    /**
     * Contralodor de mensagens
     *
     * @param controlador Escolha 1 para erro checkBox, 2 para erro subreposição
     */
    private void erro(int controlador) {
        switch (controlador) {
            case 1:
                JOptionPane.showMessageDialog(this, "Por favor, selecionar somente duas opções","Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Erro de sobreposição!","Erro", JOptionPane.ERROR_MESSAGE);
                break;
        }

    }

    private void trocar(JButton[] bDestino, JButton[] bOrigem, Pilha pDestino, Pilha pOrigem) {
        if (pOrigem.getTamanho() > 0) {
            int valor = pOrigem.pop();
            pDestino.push(valor);
            bDestino[pDestino.getTamanho() - 1].setText(String.valueOf(valor));
            bOrigem[pOrigem.getTamanho()].setText(" ");
        }
    }

    private boolean isVerificador(Pilha pDestino, Pilha pOrigem) {
        int d = pDestino.top();
        int o = pOrigem.top();
        return pDestino.top() > pOrigem.top();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnX1 = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnX3 = new javax.swing.JButton();
        btnX4 = new javax.swing.JButton();
        btnY1 = new javax.swing.JButton();
        btnY2 = new javax.swing.JButton();
        btnY3 = new javax.swing.JButton();
        btnY4 = new javax.swing.JButton();
        btnZ1 = new javax.swing.JButton();
        btnZ2 = new javax.swing.JButton();
        btnZ3 = new javax.swing.JButton();
        btnZ4 = new javax.swing.JButton();
        cbX = new javax.swing.JCheckBox();
        cbY = new javax.swing.JCheckBox();
        cbZ = new javax.swing.JCheckBox();
        btnTrocaDireita = new javax.swing.JButton();
        btnTrocaEsquerda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnX1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnX1.setEnabled(false);

        btnX2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnX2.setEnabled(false);

        btnX3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnX3.setEnabled(false);

        btnX4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnX4.setEnabled(false);

        btnY1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnY1.setEnabled(false);

        btnY2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnY2.setEnabled(false);

        btnY3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnY3.setEnabled(false);

        btnY4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnY4.setEnabled(false);

        btnZ1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZ1.setEnabled(false);

        btnZ2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZ2.setEnabled(false);

        btnZ3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZ3.setEnabled(false);

        btnZ4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZ4.setEnabled(false);

        cbX.setText("X");

        cbY.setText("Y");

        cbZ.setText("Z");

        btnTrocaDireita.setText(">");
        btnTrocaDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaDireitaActionPerformed(evt);
            }
        });

        btnTrocaEsquerda.setText("<");
        btnTrocaEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaEsquerdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnX4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cbX)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnY4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cbY)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cbZ))
                            .addComponent(btnZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTrocaDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrocaEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnY4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnY3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnY2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnY1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnX4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnX1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbY)
                    .addComponent(cbX)
                    .addComponent(cbZ))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrocaDireita)
                    .addComponent(btnTrocaEsquerda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrocaDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaDireitaActionPerformed
        if (!isVerificadorCheckBox()) {
            if (cbX.isSelected() && cbY.isSelected()) {
                if (isVerificador(Y, X)) {
                    trocar(botoesY, botoesX, Y, X);
                } else {
                    erro(2);
                }
            } else if (cbX.isSelected() && cbZ.isSelected()) {
                if (isVerificador(Z, X)) {
                    trocar(botoesZ, botoesX, Z, X);
                } else {
                    erro(2);
                }
            } else if (cbY.isSelected() && cbZ.isSelected()) {
                if (isVerificador(Z, Y)) {
                    trocar(botoesZ, botoesY, Z, Y);
                } else {
                    erro(2);
                }
            }
        } else {
            erro(1);
        }
    }//GEN-LAST:event_btnTrocaDireitaActionPerformed

    private void btnTrocaEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaEsquerdaActionPerformed
        if (!isVerificadorCheckBox()) {
            if (cbX.isSelected() && cbY.isSelected()) {
                if (isVerificador(X, Y)) {
                    trocar(botoesX, botoesY, X, Y);
                } else {
                    erro(2);
                }
            } else if (cbX.isSelected() && cbZ.isSelected()) {
                if (isVerificador(X, Z)) {
                    trocar(botoesX, botoesZ, X, Z);
                } else {
                    erro(2);
                }
            } else if (cbY.isSelected() && cbZ.isSelected()) {
                if (isVerificador(Y, Z)) {
                    trocar(botoesY, botoesZ, Y, Z);
                } else {
                    erro(2);
                }
            }
        } else {
            erro(1);
        }
    }//GEN-LAST:event_btnTrocaEsquerdaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrocaDireita;
    private javax.swing.JButton btnTrocaEsquerda;
    private javax.swing.JButton btnX1;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnX3;
    private javax.swing.JButton btnX4;
    private javax.swing.JButton btnY1;
    private javax.swing.JButton btnY2;
    private javax.swing.JButton btnY3;
    private javax.swing.JButton btnY4;
    private javax.swing.JButton btnZ1;
    private javax.swing.JButton btnZ2;
    private javax.swing.JButton btnZ3;
    private javax.swing.JButton btnZ4;
    private javax.swing.JCheckBox cbX;
    private javax.swing.JCheckBox cbY;
    private javax.swing.JCheckBox cbZ;
    // End of variables declaration//GEN-END:variables
}
