/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.view;

/**
 *
 * @author lg
 */
public class CadEditView extends javax.swing.JDialog {

    /**
     * Creates new form CadEditView
     */
    public CadEditView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNroProf = new javax.swing.JLabel();
        lblSalarioBase = new javax.swing.JLabel();
        lblFormacao = new javax.swing.JLabel();
        txtNroProfessor = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        cbFormacao = new javax.swing.JComboBox<>();
        ckEmAndamento = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Professores");

        lblNroProf.setText("Nro Prof:");

        lblSalarioBase.setText("Salário Base:");

        lblFormacao.setText("Formação:");

        cbFormacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Selecione...]", "Graduação", "Pós", "Mestrado", "Doutorado" }));

        ckEmAndamento.setText("Em andamento");

        btnCalcular.setText("Calcular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckEmAndamento)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSalario)
                                .addComponent(txtNroProfessor)
                                .addComponent(cbFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroProf)
                    .addComponent(txtNroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioBase)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormacao)
                    .addComponent(cbFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ckEmAndamento)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbFormacao;
    private javax.swing.JCheckBox ckEmAndamento;
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JLabel lblNroProf;
    private javax.swing.JLabel lblSalarioBase;
    private javax.swing.JTextField txtNroProfessor;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(javax.swing.JButton btnCalcular) {
        this.btnCalcular = btnCalcular;
    }

    public javax.swing.JComboBox<String> getCbFormacao() {
        return cbFormacao;
    }

    public void setCbFormacao(javax.swing.JComboBox<String> cbFormacao) {
        this.cbFormacao = cbFormacao;
    }

    public javax.swing.JCheckBox getCkEmAndamento() {
        return ckEmAndamento;
    }

    public void setCkEmAndamento(javax.swing.JCheckBox ckEmAndamento) {
        this.ckEmAndamento = ckEmAndamento;
    }

    public javax.swing.JLabel getLblFormacao() {
        return lblFormacao;
    }

    public void setLblFormacao(javax.swing.JLabel lblFormacao) {
        this.lblFormacao = lblFormacao;
    }

    public javax.swing.JLabel getLblNroProf() {
        return lblNroProf;
    }

    public void setLblNroProf(javax.swing.JLabel lblNroProf) {
        this.lblNroProf = lblNroProf;
    }

    public javax.swing.JLabel getLblSalarioBase() {
        return lblSalarioBase;
    }

    public void setLblSalarioBase(javax.swing.JLabel lblSalarioBase) {
        this.lblSalarioBase = lblSalarioBase;
    }

    public javax.swing.JTextField getTxtNroProfessor() {
        return txtNroProfessor;
    }

    public void setTxtNroProfessor(javax.swing.JTextField txtNroProfessor) {
        this.txtNroProfessor = txtNroProfessor;
    }

    public javax.swing.JTextField getTxtSalario() {
        return txtSalario;
    }

    public void setTxtSalario(javax.swing.JTextField txtSalario) {
        this.txtSalario = txtSalario;
    }

}
