package br.edu.qi.entity;
// Generated 29/11/2017 21:51:45 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu",
         catalog = "refeicao"
)
public class Menu implements java.io.Serializable {

    private Integer idMenu;
    private Instituicao instituicao;
    private Refeicao refeicao;
    private Date dataCarpadio;
    private String descricao;

    public Menu() {
    }

    public Menu(Date dataCarpadio) {
        this.dataCarpadio = dataCarpadio;
    }

    public Menu(Instituicao instituicao, Refeicao refeicao, Date dataCarpadio, String descricao) {
        this.instituicao = instituicao;
        this.refeicao = refeicao;
        this.dataCarpadio = dataCarpadio;
        this.descricao = descricao;
    }

    public Menu(Integer idMenu, Instituicao instituicao, Refeicao refeicao, Date dataCarpadio, String descricao) {
        this.idMenu = idMenu;
        this.instituicao = instituicao;
        this.refeicao = refeicao;
        this.dataCarpadio = dataCarpadio;
        this.descricao = descricao;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_menu", unique = true, nullable = false)
    public Integer getIdMenu() {
        return this.idMenu;
    }

    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_instituicao")
    public Instituicao getInstituicao() {
        return this.instituicao;
    }

    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_refeicao")
    public Refeicao getRefeicao() {
        return this.refeicao;
    }

    public void setRefeicao(Refeicao refeicao) {
        this.refeicao = refeicao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_carpadio", nullable = false, length = 19)
    public Date getDataCarpadio() {
        return this.dataCarpadio;
    }

    public void setDataCarpadio(Date dataCarpadio) {
        this.dataCarpadio = dataCarpadio;
    }

    @Column(name = "descricao", length = 1000)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.instituicao);
        hash = 97 * hash + Objects.hashCode(this.refeicao);
        hash = 97 * hash + Objects.hashCode(this.dataCarpadio);
        hash = 97 * hash + Objects.hashCode(this.descricao);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Menu other = (Menu) obj;
        if (!Objects.equals(this.descricao, other.descricao)) {
            return false;
        }
        if (!Objects.equals(this.instituicao, other.instituicao)) {
            return false;
        }
        if (!Objects.equals(this.refeicao, other.refeicao)) {
            return false;
        }
        return Objects.equals(this.dataCarpadio, other.dataCarpadio);
    }

}
