package br.edu.qi.entity;
// Generated 29/11/2017 21:51:45 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParametroEmail generated by hbm2java
 */
@Entity
@Table(name = "parametro_email",
         catalog = "refeicao"
)
public class ParametroEmail implements java.io.Serializable {

    private Integer idParametroEmail;
    private String email;

    public ParametroEmail() {
    }

    public ParametroEmail(String email) {
        this.email = email;
    }

    public ParametroEmail(Integer idParametroEmail, String email) {
        this.idParametroEmail = idParametroEmail;
        this.email = email;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_parametro_email", unique = true, nullable = false)
    public Integer getIdParametroEmail() {
        return this.idParametroEmail;
    }

    public void setIdParametroEmail(Integer idParametroEmail) {
        this.idParametroEmail = idParametroEmail;
    }

    @Column(name = "email", length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return email;
    }

}
