/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.view;

import javax.swing.JTextField;

/**
 *
 * @author Luis Gustavo
 */
public class LocEditView extends javax.swing.JDialog {

    /**
     * Creates new form LocEditView
     */
    public LocEditView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNroLocacao = new javax.swing.JLabel();
        txtNroLocacao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lblMulta = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        lblQtdeDias = new javax.swing.JLabel();
        lblQtdeDiasAtraso = new javax.swing.JLabel();
        txtQtdeDiasAtraso = new javax.swing.JTextField();
        txtQtdeDias = new javax.swing.JTextField();
        lblVeiculo = new javax.swing.JLabel();
        cbVeiculo = new javax.swing.JComboBox<>();
        lblAvista = new javax.swing.JLabel();
        ckAvista = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNroLocacao.setText("Número da Locação");

        lblValor.setText("Valor");

        lblMulta.setText("Multa");

        lblQtdeDias.setText("QtdeDias");

        lblQtdeDiasAtraso.setText("QtdeDiasAtraso");

        lblVeiculo.setText("Veiculo ");

        cbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Selecione...]", "Meriva - 140", "Corsa - 100", "Fox - 130", "Palio - 90" }));

        lblAvista.setText("À vista");

        btnCalcular.setText("Calcular");

        jLabel8.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNroLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNroLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnCalcular)
                                        .addGap(0, 28, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAvista)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckAvista)))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMulta)
                                    .addComponent(lblValor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(txtMulta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtdeDiasAtraso)
                                    .addComponent(lblQtdeDias))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtdeDias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQtdeDiasAtraso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroLocacao)
                    .addComponent(txtNroLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVeiculo)
                    .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdeDias)
                    .addComponent(txtQtdeDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMulta)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdeDiasAtraso)
                    .addComponent(txtQtdeDiasAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvista)
                    .addComponent(ckAvista))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(jLabel8)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LocEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LocEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LocEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LocEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                LocEditView dialog = new LocEditView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbVeiculo;
    private javax.swing.JCheckBox ckAvista;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAvista;
    private javax.swing.JLabel lblMulta;
    private javax.swing.JLabel lblNroLocacao;
    private javax.swing.JLabel lblQtdeDias;
    private javax.swing.JLabel lblQtdeDiasAtraso;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtNroLocacao;
    private javax.swing.JTextField txtQtdeDias;
    private javax.swing.JTextField txtQtdeDiasAtraso;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(javax.swing.JButton btnCalcular) {
        this.btnCalcular = btnCalcular;
    }

    public javax.swing.JComboBox<String> getCbVeiculo() {
        return cbVeiculo;
    }

    public void setCbVeiculo(javax.swing.JComboBox<String> cbVeiculo) {
        this.cbVeiculo = cbVeiculo;
    }

    public javax.swing.JCheckBox getCkAvista() {
        return ckAvista;
    }

    public void setCkAvista(javax.swing.JCheckBox ckAvista) {
        this.ckAvista = ckAvista;
    }

    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public javax.swing.JLabel getLblAvista() {
        return lblAvista;
    }

    public void setLblAvista(javax.swing.JLabel lblAvista) {
        this.lblAvista = lblAvista;
    }

    public javax.swing.JLabel getLblMulta() {
        return lblMulta;
    }

    public void setLblMulta(javax.swing.JLabel lblMulta) {
        this.lblMulta = lblMulta;
    }

    public javax.swing.JLabel getLblNroLocacao() {
        return lblNroLocacao;
    }

    public void setLblNroLocacao(javax.swing.JLabel lblNroLocacao) {
        this.lblNroLocacao = lblNroLocacao;
    }

    public javax.swing.JLabel getLblQtdeDias() {
        return lblQtdeDias;
    }

    public void setLblQtdeDias(javax.swing.JLabel lblQtdeDias) {
        this.lblQtdeDias = lblQtdeDias;
    }

    public javax.swing.JLabel getLblQtdeDiasAtraso() {
        return lblQtdeDiasAtraso;
    }

    public void setLblQtdeDiasAtraso(javax.swing.JLabel lblQtdeDiasAtraso) {
        this.lblQtdeDiasAtraso = lblQtdeDiasAtraso;
    }

    public javax.swing.JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(javax.swing.JLabel lblValor) {
        this.lblValor = lblValor;
    }

    public javax.swing.JLabel getLblVeiculo() {
        return lblVeiculo;
    }

    public void setLblVeiculo(javax.swing.JLabel lblVeiculo) {
        this.lblVeiculo = lblVeiculo;
    }

    public javax.swing.JTextField getTxtMulta() {
        return txtMulta;
    }

    public void setTxtMulta(javax.swing.JTextField txtMulta) {
        this.txtMulta = txtMulta;
    }

    public javax.swing.JTextField getTxtNroLocacao() {
        return txtNroLocacao;
    }

    public void setTxtNroLocacao(javax.swing.JTextField txtNroLocacao) {
        this.txtNroLocacao = txtNroLocacao;
    }

    public javax.swing.JTextField getTxtQtdeDias() {
        return txtQtdeDias;
    }

    public void setTxtQtdeDias(javax.swing.JTextField txtQtdeDias) {
        this.txtQtdeDias = txtQtdeDias;
    }

    public javax.swing.JTextField getTxtQtdeDiasAtraso() {
        return txtQtdeDiasAtraso;
    }

    public void setTxtQtdeDiasAtraso(javax.swing.JTextField txtQtdeDiasAtraso) {
        this.txtQtdeDiasAtraso = txtQtdeDiasAtraso;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public void setTxtTotal(JTextField txtTotal) {
        this.txtTotal = txtTotal;
    }

    
    public javax.swing.JTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(javax.swing.JTextField txtValor) {
        this.txtValor = txtValor;
    }

    
    
}
