package br.edu.qi.model;
// Generated 02/11/2017 10:18:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carro generated by hbm2java
 */
@Entity
@Table(name = "carro",
        catalog = "dbrevenda"
)
public class Carro implements java.io.Serializable {

    private Integer idCarro;
    private Marca marca;
    private Modelo modelo;
    private Set<Venda> vendas = new HashSet<Venda>(0);

    public Carro() {
    }

    public Carro(Marca marca, Modelo modelo, Set<Venda> vendas) {
        this.marca = marca;
        this.modelo = modelo;
        this.vendas = vendas;
    }

    public Carro(String selecione) {
        this.modelo.setDescricao(selecione); 
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_carro", unique = true, nullable = false)
    public Integer getIdCarro() {
        return this.idCarro;
    }

    public void setIdCarro(Integer idCarro) {
        this.idCarro = idCarro;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_marca")
    public Marca getMarca() {
        return this.marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_modelo")
    public Modelo getModelo() {
        return this.modelo;
    }

    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "carro")
    public Set<Venda> getVendas() {
        return this.vendas;
    }

    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.marca);
        hash = 11 * hash + Objects.hashCode(this.modelo);
        return hash;
    }

    public boolean equals(Carro obj) {
        return this.marca.getIdMarca() == obj.getMarca().getIdMarca()
                && this.modelo.getIdModelo() == obj.getModelo().getIdModelo();
    }

    @Override
    public String toString() {
       return modelo.toString() + "-" + marca.toString();
    }

}
