package br.edu.qi.model;
// Generated 02/11/2017 10:18:25 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento",
        catalog = "dbrevenda"
)
public class Pagamento implements java.io.Serializable, Comparable<Pagamento> {

    private Integer idPagamento;
    private Venda venda;
    private String nroPagamento;
    private Date dataVencimento;
    private Date dataPagamento;
    private BigDecimal multa;
    private BigDecimal valorLiquido;
    private Byte liquidacao;

    public Pagamento() {
    }

    public Pagamento(String nroPagamento, Date dataVencimento) {
        this.nroPagamento = nroPagamento;
        this.dataVencimento = dataVencimento;
    }

    public Pagamento(String nroPagamento, Venda venda,Date dataVencimento, BigDecimal valorLiquido) {
        this.nroPagamento = nroPagamento;
        this.venda = venda;
        this.dataVencimento = dataVencimento;
        this.valorLiquido = valorLiquido;
    }

    public Pagamento(Venda venda, String nroPagamento, Date dataVencimento, Date dataPagamento, BigDecimal multa, BigDecimal valorLiquido, Byte liquidacao) {
        this.venda = venda;
        this.nroPagamento = nroPagamento;
        this.dataVencimento = dataVencimento;
        this.dataPagamento = dataPagamento;
        this.multa = multa;
        this.valorLiquido = valorLiquido;
        this.liquidacao = liquidacao;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_pagamento", unique = true, nullable = false)
    public Integer getIdPagamento() {
        return this.idPagamento;
    }

    public void setIdPagamento(Integer idPagamento) {
        this.idPagamento = idPagamento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_venda")
    public Venda getVenda() {
        return this.venda;
    }

    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    @Column(name = "nro_pagamento", nullable = false, length = 10)
    public String getNroPagamento() {
        return this.nroPagamento;
    }

    public void setNroPagamento(String nroPagamento) {
        this.nroPagamento = nroPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_vencimento", nullable = false, length = 10)
    public Date getDataVencimento() {
        return this.dataVencimento;
    }

    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_pagamento", length = 10)
    public Date getDataPagamento() {
        return this.dataPagamento;
    }

    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    @Column(name = "multa", precision = 10)
    public BigDecimal getMulta() {
        return this.multa;
    }

    public void setMulta(BigDecimal multa) {
        this.multa = multa;
    }

    @Column(name = "valor_liquido", precision = 10)
    public BigDecimal getValorLiquido() {
        return this.valorLiquido;
    }

    public void setValorLiquido(BigDecimal valorLiquido) {
        this.valorLiquido = valorLiquido;
    }

    @Column(name = "liquidacao")
    public Byte getLiquidacao() {
        return this.liquidacao;
    }

    public void setLiquidacao(Byte liquidacao) {
        this.liquidacao = liquidacao;
    }

    @Override
    public int compareTo(Pagamento o) {
        return this.getIdPagamento().compareTo(o.getIdPagamento());
    }

}
