package br.edu.qi.model;
// Generated 02/11/2017 10:18:25 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name = "venda",
        catalog = "dbrevenda"
)
public class Venda implements java.io.Serializable {

    private Integer idVenda;
    private Carro carro;
    private Proprietario proprietario;
    private int nro;
    private Date dataVenda;
    private int ano;
    private String descricao;
    private Byte arCondicionado;
    private Byte tocaFita;
    private Byte rodaLiga;
    private Byte tapete;
    private Byte alarme;
    private String tipo;
    private String estado;
    private int km;
    private BigDecimal valor;
    private int numeroParcela;
    private Set<Pagamento> pagamentos = new HashSet<Pagamento>(0);

    public Venda() {
    }

    public Venda(int nro, Date dataVenda, int ano, String tipo, String estado, int km, BigDecimal valor, int numeroParcela) {
        this.nro = nro;
        this.dataVenda = dataVenda;
        this.ano = ano;
        this.tipo = tipo;
        this.estado = estado;
        this.km = km;
        this.valor = valor;
        this.numeroParcela = numeroParcela;
    }

    public Venda(Carro carro, Proprietario proprietario, int nro, Date dataVenda, int ano, String descricao, Byte arCondicionado, Byte tocaFita, Byte rodaLiga, Byte tapete, Byte alarme, String tipo, String estado, int km, BigDecimal valor, int numeroParcela, Set<Pagamento> pagamentos) {
        this.carro = carro;
        this.proprietario = proprietario;
        this.nro = nro;
        this.dataVenda = dataVenda;
        this.ano = ano;
        this.descricao = descricao;
        this.arCondicionado = arCondicionado;
        this.tocaFita = tocaFita;
        this.rodaLiga = rodaLiga;
        this.tapete = tapete;
        this.alarme = alarme;
        this.tipo = tipo;
        this.estado = estado;
        this.km = km;
        this.valor = valor;
        this.numeroParcela = numeroParcela;
        this.pagamentos = pagamentos;
    }

    public Venda(Carro carro, Proprietario proprietario, int nro, Date dataVenda, int ano, String descricao, Byte arCondicionado, Byte tocaFita, Byte rodaLiga, Byte tapete, Byte alarme, String tipo, String estado, int km, BigDecimal valor, int numeroParcela) {
        this.carro = carro;
        this.proprietario = proprietario;
        this.nro = nro;
        this.dataVenda = dataVenda;
        this.ano = ano;
        this.descricao = descricao;
        this.arCondicionado = arCondicionado;
        this.tocaFita = tocaFita;
        this.rodaLiga = rodaLiga;
        this.tapete = tapete;
        this.alarme = alarme;
        this.tipo = tipo;
        this.estado = estado;
        this.km = km;
        this.valor = valor;
        this.numeroParcela = numeroParcela;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_venda", unique = true, nullable = false)
    public Integer getIdVenda() {
        return this.idVenda;
    }

    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_carro")
    public Carro getCarro() {
        return this.carro;
    }

    public void setCarro(Carro carro) {
        this.carro = carro;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_proprietario")
    public Proprietario getProprietario() {
        return this.proprietario;
    }

    public void setProprietario(Proprietario proprietario) {
        this.proprietario = proprietario;
    }

    @Column(name = "nro", nullable = false)
    public int getNro() {
        return this.nro;
    }

    public void setNro(int nro) {
        this.nro = nro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_venda", nullable = false, length = 10)
    public Date getDataVenda() {
        return this.dataVenda;
    }

    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

    @Column(name = "ano", nullable = false)
    public int getAno() {
        return this.ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    @Column(name = "descricao", length = 1000)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "ar_condicionado")
    public Byte getArCondicionado() {
        return this.arCondicionado;
    }

    public void setArCondicionado(Byte arCondicionado) {
        this.arCondicionado = arCondicionado;
    }

    @Column(name = "toca_fita")
    public Byte getTocaFita() {
        return this.tocaFita;
    }

    public void setTocaFita(Byte tocaFita) {
        this.tocaFita = tocaFita;
    }

    @Column(name = "roda_liga")
    public Byte getRodaLiga() {
        return this.rodaLiga;
    }

    public void setRodaLiga(Byte rodaLiga) {
        this.rodaLiga = rodaLiga;
    }

    @Column(name = "tapete")
    public Byte getTapete() {
        return this.tapete;
    }

    public void setTapete(Byte tapete) {
        this.tapete = tapete;
    }

    @Column(name = "alarme")
    public Byte getAlarme() {
        return this.alarme;
    }

    public void setAlarme(Byte alarme) {
        this.alarme = alarme;
    }

    @Column(name = "tipo", nullable = false, length = 50)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Column(name = "estado", nullable = false, length = 50)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "km", nullable = false)
    public int getKm() {
        return this.km;
    }

    public void setKm(int km) {
        this.km = km;
    }

    @Column(name = "valor", nullable = false, precision = 10)
    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Column(name = "numero_parcela", nullable = false)
    public int getNumeroParcela() {
        return this.numeroParcela;
    }

    public void setNumeroParcela(int numeroParcela) {
        this.numeroParcela = numeroParcela;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "venda")
    public Set<Pagamento> getPagamentos() {
        return this.pagamentos;
    }

    public void setPagamentos(Set<Pagamento> pagamentos) {
        this.pagamentos = pagamentos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + this.nro;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Venda other = (Venda) obj;
        if (this.nro != other.nro) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return proprietario.toString();
    }
    
    

}
