/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import node.Lista;

/**
 *
 * @author Luis Gustavo
 */
public class FrmEdicao extends javax.swing.JFrame {

    /**
     * Creates new form FrmEdicao
     */
    public FrmEdicao() {
        initComponents();
        carregarInformacao();
    }

    private void carregarInformacao() {
        if (FrmAlunos.controleEdicao) {
            txtNome.setText(FrmAlunos.nomeAnterior);
            txtCurso.setText(FrmAlunos.cursoAnterior);
        }
    }

    private void limpaCampos() {
        txtNome.setText("");
        txtCurso.setText("");
    }

    private void editarAluno() {
        if (!FrmAlunos.cursoAnterior.equals(txtCurso.getText()) || !FrmAlunos.nomeAnterior.equals(txtNome.getText())) {
            boolean status = Lista.isEdicaoAluno(FrmAlunos.codigoAnterior, txtNome.getText(), txtCurso.getText());
            if (status) {
                limpaCampos();
                JOptionPane.showMessageDialog(this, "Aluno alterado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível alterar o registro!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível, pois, os registros não foram alterados!");
        }

    }

    private void novoAluno() {
        if (txtNome.getText().isEmpty() || txtCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro, não foi possivel cadastrar livro!\nPreencha todos os campos!");
        } else {
            boolean status = Lista.isCadastrarAluno(txtNome.getText(), txtCurso.getText());
            if (status) {
                limpaCampos();
                JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Old English Text MT", 3, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Aluno");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 354, 52));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 99, -1, -1));

        lblCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurso.setText("Curso:");
        getContentPane().add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 137, -1, -1));
        getContentPane().add(txtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 137, 266, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 99, 266, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 175, 100, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 175, 100, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (FrmAlunos.controleEdicao) {
            editarAluno();
        } else {
            novoAluno();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

}
