/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.view;

/**
 *
 * @author Luis Gustavo
 */
public class CadastroMatriculaEditView extends javax.swing.JDialog {

    /**
     * Creates new form cadastroMatriculaEditView
     */
    public CadastroMatriculaEditView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNroMatricula = new javax.swing.JLabel();
        lblDisciplina = new javax.swing.JLabel();
        lblDesconto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtNroMatricula = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        cbDisciplina = new javax.swing.JComboBox<>();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição Matricula");
        setAutoRequestFocus(false);
        setResizable(false);

        lblNroMatricula.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblNroMatricula.setText("Número Matricula");

        lblDisciplina.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblDisciplina.setText("Disciplina");

        lblDesconto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblDesconto.setText("Desconto %");

        lblTotal.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblTotal.setText("Total");

        txtNroMatricula.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        txtDesconto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescontoActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        cbDisciplina.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Selecione...]", "BD I", "Algorítmos", "SO", "Lógica Computacional", "BD Aplicado", "Serviços Web" }));

        btnGravar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDisciplina)
                                    .addComponent(lblDesconto)
                                    .addComponent(lblTotal))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNroMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnGravar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroMatricula)
                    .addComponent(txtNroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplina)
                    .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesconto)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<String> cbDisciplina;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblNroMatricula;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtNroMatricula;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnGravar() {
        return btnGravar;
    }

    public void setBtnGravar(javax.swing.JButton btnGravar) {
        this.btnGravar = btnGravar;
    }

    public javax.swing.JComboBox<String> getCbDisciplina() {
        return cbDisciplina;
    }

    public void setCbDisciplina(javax.swing.JComboBox<String> cbDisciplina) {
        this.cbDisciplina = cbDisciplina;
    }

    public javax.swing.JLabel getLblDesconto() {
        return lblDesconto;
    }

    public void setLblDesconto(javax.swing.JLabel lblDesconto) {
        this.lblDesconto = lblDesconto;
    }

    public javax.swing.JLabel getLblDisciplina() {
        return lblDisciplina;
    }

    public void setLblDisciplina(javax.swing.JLabel lblDisciplina) {
        this.lblDisciplina = lblDisciplina;
    }

    public javax.swing.JLabel getLblNroMatricula() {
        return lblNroMatricula;
    }

    public void setLblNroMatricula(javax.swing.JLabel lblNroMatricula) {
        this.lblNroMatricula = lblNroMatricula;
    }

    public javax.swing.JLabel getLblTotal() {
        return lblTotal;
    }

    public void setLblTotal(javax.swing.JLabel lblTotal) {
        this.lblTotal = lblTotal;
    }

    public javax.swing.JTextField getTxtDesconto() {
        return txtDesconto;
    }

    public void setTxtDesconto(javax.swing.JTextField txtDesconto) {
        this.txtDesconto = txtDesconto;
    }

    public javax.swing.JTextField getTxtNroMatricula() {
        return txtNroMatricula;
    }

    public void setTxtNroMatricula(javax.swing.JTextField txtNroMatricula) {
        this.txtNroMatricula = txtNroMatricula;
    }

    public javax.swing.JTextField getTxtTotal() {
        return txtTotal;
    }

    public void setTxtTotal(javax.swing.JTextField txtTotal) {
        this.txtTotal = txtTotal;
    }

  
    
}
